### ISSUE TITLE
10X Genomics data in hapCUT2

### ISSUE THREAD

**Issue by burri-wildlight** [vibansal/HapCUT2#90]
Dear Peter,

We were hoping that hapCUT2 would allow us to skip LongRanger to phase variants. However, we are running into some issues, and I would like to check back with you regarding some questions. Ultimately, our major problem is that after preparing the linked fragment files, hapCUT2 reliably produces a segmentation fault (please see below). We've tried to exclude problems with the input, but so far were unable to figure it out.

I was therefore wondering about the following:
1. We run alignments using Lariat in LongRanger (longranger align). This includes the barcodes in the BX field, but does not provide phase in the bam file. For this the entire LongRanger pipeline would have to be run, something we hope to skip.
2. I am not sure whether the fragment and the linked fragment files indeed contain all there is. Would it be possible for you to share ones against which we could check ours? Or alternatively, would you be ok to have a look at our input?

Thanks a lot & very best wishes,
Reto

** ERROR
[2020:02:06 09:51:42] fragment file: /data/oenanthe/data/10XG_data/phased_vcf_hapcut2/GEO-CHA-2018-013.linked_fragment.file
[2020:02:06 09:51:42] variantfile (VCF format):test_hapcut.vcf
[2020:02:06 09:51:42] haplotypes will be output to file: /data/oenanthe/data/10XG_data/phased_vcf_hapcut2/GEO-CHA-2018-013.hapCUT2.out
[2020:02:06 09:51:42] solution convergence cutoff: 5
[2020:02:06 09:51:42] QVoffset: 33

[2020:02:06 09:51:42] Calling Max-Likelihood-Cut based haplotype assembly algorithm
[2020:02:06 09:52:09] read 29654 variants from test_hapcut.vcf file
Segmentation fault

**Comment by FrickTobias** [comment]
I had a similar problem, and I think this should be solved with the last commits specified in the last comment on #77. So I'd try updating HapCUT2 to the latest version on GitHub.

**Comment by burri-wildlight** [comment]
Thanks a lot Tobias! So far I am running a conda version (hed50d52_0 from 3 months ago), which might be fresh enough to contain the fix you mention, or just not. I'll anyway try and see what comes out of it. In the meantime we're fighting also with the LinkFragments.py script, which executes on the terminal but not on compute nodes (though on the latter calling on it without arguments will show the help). If anyone has inputs on what kind of (even very basic) issues could cause this, I'd also be very grateful! Best, Reto

**Comment by FrickTobias** [comment]
The `conda` version does not contain that change, you need to run the GitHub version or wait until there is a new release.

**Comment by burri-wildlight** [comment]
Thanks a ton for this info Tobias!!

**Comment by burri-wildlight** [comment]
Hi Tobias, hi Peter,

We have now installed everything as pointed out above, but still get the Segmentation fault. We are going to look into the core dump on Monday to figure out what might be going on. In the mean, I was wondering if you would be willing to share a functional fragments and linked-fragments files ( reto dot burri at uni-jena  dot de? Or have a look at the below? I am wondering whether something with what we're running is going wrong already at this step, as in the fragment file we have entries without indices.

Some lines from the fragment file:
1 A00187:220:HTV25DSXX:3:1175:10981:6073 2 TAAACCGGTACGTAAA-1 -1 30 00 FF
1 A00187:220:HTV25DSXX:3:1152:3432:6621 2 TTGAACGCAAGAAAGG-1 -1 30 000101 ======
1 A00187:220:HTV25DSXX:3:2214:17472:4038 2 GGCCGATTCGGAGGTA-1 -1 30 000101 :FFF:F
1 A00187:220:HTV25DSXX:3:2214:17707:31438 2 GGCCGATTCGGAGGTA-1 -1 30 000101 FFF:FF
1 A00187:220:HTV25DSXX:3:1350:31494:20932 2 NULL -1 30 000101 FFF:FF
1 A00187:220:HTV25DSXX:3:1310:11017:36010 2 TGCCCATTCACAGTAC-1 -1 30 000000 FFFFFF
1 A00187:220:HTV25DSXX:3:2277:28357:22263 2 ACCCGTTCATCCGGGT-1 -1 30 000101 :FFFFF
1 A00187:220:HTV25DSXX:3:1632:24912:4116 2 ACTTTCATCAATAGAG-1 -1 31 00000 FFFFF
1 A00187:220:HTV25DSXX:3:1228:26368:18850 2 TGTACGAAGATCACTC-1 -1 32 0000 FFFF
1 A00187:220:HTV25DSXX:3:1572:27037:26052 2 ACCCAAATCAATACCG-1 -1 32 0101 FFFF
1 A00187:220:HTV25DSXX:3:1349:14064:30264 2 GGCGGTTCAACTCATG-1 -1 35 0 5
1 A00187:220:HTV25DSXX:3:2357:12246:2096 2 GCTAATGAGGACACCA-1 -1 35 0 F
1 A00187:220:HTV25DSXX:3:2504:29866:33238 2 CGGATCGTCCACGATA-1 -1 37 0 F
1 A00187:220:HTV25DSXX:3:2310:16776:17989 2 TGGGCTGTCACCAGGC-1 -1 39 0 5
1 A00187:220:HTV25DSXX:3:1630:27624:29293 2 GGACATTCACACTAAC-1 -1 43 10 BB
1 A00187:220:HTV25DSXX:3:2610:13612:4022 2 CATGACACACTGTTCC-1 -1 49 0 F
1 A00187:220:HTV25DSXX:3:1273:16514:20259 2 TGTAGTGAGGTAACGC-1 -1 49 1 F
1 A00187:220:HTV25DSXX:3:2272:10149:21292 2 TGTAGTGAGGTAACGC-1 -1 49 1 F
1 A00187:220:HTV25DSXX:3:2456:24867:32440 2 GCATACATCTGCAAGT-1 -1 49 0 F
1 A00187:220:HTV25DSXX:3:1120:15049:1282 2 NULL -1 55 0 5
1 A00187:220:HTV25DSXX:3:2605:7175:18521 2 TAGGCCGAGAGTAGCC-1 -1 56 1 F
1 A00187:220:HTV25DSXX:3:2644:32045:7106 2 NULL -1 56 1 F
1 A00187:220:HTV25DSXX:3:1321:5502:1720 2 GTCGGGTGTGATGTAA-1 -1 56 0 :
1 A00187:220:HTV25DSXX:3:1210:26549:22169 2 TACCTATCAGGGAGAG-1 -1 56 0 :
1 A00187:220:HTV25DSXX:3:2142:8377:21793 2 NULL -1 56 0 F
1 A00187:220:HTV25DSXX:3:1453:13928:2879 2 TCCCTTTCAATGGACG-1 -1 56 1 F


Some linkes from the linked-fragment file
1 000000F|arrow:41828-52926:GCATGATTCCCGGTAG-1 0 -1 -1 8 00 FF
1 000000F|arrow:45846-45928:GTGGCACGTGTCAACT-1 0 -1 -1 8 11 DD
1 000000F|arrow:45848-49815:GGACAGATCAGCATGT-1 0 -1 -1 8 001 FFF
1 000000F|arrow:45858-45928:TGACTGAAGCTTATCG-1 0 -1 -1 8 11 @@
1 000000F|arrow:49708-50034:TGTGGTATCGGCCGAT-1 0 -1 -1 10 100 FF:
1 000000F|arrow:49732-50112:CCGTCATTCCTATTCA-1 0 -1 -1 10 011 555
1 000000F|arrow:48147-50576:TGAGACTAGAAGTTCA-1 0 -1 -1 11 111 FFF
1 000000F|arrow:49581-50115:AATCCAGGTTGAACTC-1 0 -1 -1 11 11 FF
1 000000F|arrow:49889-50284:CTCTAGCAGTCACGCC-1 0 -1 -1 11 11 55
1 000000F|arrow:49897-50525:CTGCATCAGTTGGGCA-1 0 -1 -1 11 000 FFF
1 000000F|arrow:49902-50301:TGTATTCAGGGTCAAC-1 0 -1 -1 11 11 55
1 000000F|arrow:49941-50346:TCGGGCAAGCATCCGC-1 0 -1 -1 11 11 55
1 000000F|arrow:49977-50128:TCGTACCTCGTCCCTA-1 0 -1 -1 11 00 55
1 A00187:220:HTV25DSXX:3:1125:21766:29324 0 -1 -1 11 00 55
2 000000F|arrow:49941-50562:ACGCTAACAAATTCCG-1 0 -1 -1 11 0 13 0 FF
1 000000F|arrow:76340-115478:GGGAATGCACATACAC-1 0 -1 -1 16 111 555
1 000000F|arrow:94738-95351:GTGCTCTTCCTACAGA-1 0 -1 -1 16 00 55
1 000000F|arrow:94859-95351:GCTCCTAAGCAATTAG-1 0 -1 -1 16 00 55
1 000000F|arrow:94953-95373:CGGAACCCACACTGCG-1 0 -1 -1 16 11 55

Thanks a ton!
Reto

**Comment by vibansal** [comment]
Can you share your input files (or a sample of them) so that I can reproduce the error and debug? You can send them via email to vibansal at ucsd.edu

**Comment by chunlinxiao** [comment]
Does the v1.2 contains all the new fixes from Issue #77 related to “UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 ?

thanks

**Comment by vibansal** [comment]
No, it doesn't. Please try the code in branch 'merging_021820'. If the error still persists, I can take a look at your input file to figure out the problem.
